---
# handlers file for ansible-role-haproxy

- name: Restart haproxy on Linux
  service:
    name: "{{ haproxy_service }}"
    state: restarted

- name: Restart haproxy on FreeBSD
  service:
    name: "{{ haproxy_service }}"
    state: restarted
