---
# tasks file for install haproxy package on FreeBSD system

- name: Add haproxy group on FreeBSD system
  group:
    name: haproxy
    state: present

- name: Add haproxy user on FreeBSD system
  user:
    name: haproxy
    comment: Haproxy user
    group: haproxy
    shell: /sbin/nologin
    state: present

- name: Install haproxy on FreeBSD system
  package:
    name: haproxy
    state: present
