---
# tasks file for install haproxy package on OpenBSD system

- name: Add haproxy group on OpenBSD system
  group:
    name: haproxy
    state: present

- name: Add haproxy user on OpenBSD system
  user:
    name: haproxy
    comment: Haproxy user
    group: haproxy
    shell: /sbin/nologin
    state: present

- name: Install haproxy on OpenBSD system
  package:
    name: haproxy
    state: present
